#!/bin/sh
# tv_grab_file for TimeFor.TV XMLTV file
dflag=
vflag=
cflag=
if [ $# = 0 ]
then
    wget -q -O /tmp/epg.xml http://timefor.tv/xmltv/###YOUR_SECRET_HASH###
    sed -i 's/id=\"www.timefor.tv\/tv\//id=\"/g' /tmp/epg.xml
    sed -i 's/channel=\"www.timefor.tv\/tv\//channel=\"/g' /tmp/epg.xml
    cat /tmp/epg.xml
    rm /tmp/epg.xml
    exit 0
fi

for arg
do
    delim=""
    case "$arg" in
    #translate --gnu-long-options to -g (short options)
       --description) args="${args}-d ";;
       --version) args="${args}-v ";;
       --capabilities) args="${args}-c ";;
       #pass through anything else
       *) [[ "${arg:0:1}" == "-" ]] || delim="\""
           args="${args}${delim}${arg}${delim} ";;
    esac
done

eval set -- $args

while getopts "dvc" option
do
    case $option in
        d)  dflag=1;;
        v)  vflag=1;;
        c)  cflag=1;;
        \?) printf "unknown option: -%s\n" $OPTARG
            printf "Usage: %s: [--description] [--version] [--capabilities] \n" $(basename $0)
            exit 2
            ;;
    esac >&2
done

if [ "$dflag" ]
then
   printf "TimeFor.TV"
fi
if [ "$vflag" ]
then
   printf "1.0\n"
fi
if [ "$cflag" ]
then
   printf "baseline\n"
fi

exit 0
